jobs:
  ci:
    name: Run
    runs-on: ubuntu-20.04

    steps:
      - name: Begin
        uses: actions/checkout@v2
      - name: Download Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Test
        run: ./workflow/ci

name: Main

on:
  schedule:
    - cron: "5 0/3 * * *"
